# Generated by Django 4.1.2 on 2023-06-17 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='id de producto')),
                ('precio', models.IntegerField(blank=True, max_length=10, verbose_name='Precio')),
                ('stock', models.IntegerField(blank=True, max_length=5, verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=30, verbose_name='Nombre producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mascotas.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
